---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: farmos
  name: farmos
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path
  volumeMode: Filesystem
