---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared
data:
  config.yaml: |
    # Name of the tunnel you want to run
    tunnel: {{ .Values.tunnel.name }}
    credentials-file: /etc/cloudflared/creds/credentials.json
    # Serves the metrics server under /metrics and the readiness server under /ready
    metrics: 0.0.0.0:2000
    # Autoupdates applied in a k8s pod will be lost when the pod is removed or restarted, so
    # autoupdate doesn't make sense in Kubernetes.
    no-autoupdate: true
    ingress:
      - hostname: {{ .Values.tunnel.hostname }}
        service: http://{{ .Values.tunnel.service }}:{{ .Values.tunnel.port }}
      # This rule matches any traffic which didn't match, and responds with HTTP 404.
      - service: http_status:404
