---
replicaCount: 1

image:
  repository: jellyfin/jellyfin
  tag: 10.10.7
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 8096

ingress:
  enabled: false

persistence:
  config:
    enabled: true
    ## If you want to reuse an existing claim, you can pass the name of the PVC using
    ## the existingClaim variable
    # existingClaim: your-claim
    # subPath: some-subpath
    accessMode: ReadWriteOnce
    size: 1Gi
  media:
    enabled: false
    accessMode: ReadWriteOnce
    size: 10Gi
  extraExistingClaimMounts: []
    # - name: external-mount
    #   mountPath: /srv/external-mount
    ## A manually managed Persistent Volume and Claim
    ## If defined, PVC must be created manually before volume will be bound
    #   existingClaim:
    #   readOnly: true

resources:
  limits:
    memory: 12Gi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

extraVolumes:
  - name: jammaraid
    hostPath:
      path: /media/raid/jammaraid

extraVolumeMounts:
  - mountPath: /media/raid/jammaraid
    name: jammaraid
