apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mariadb
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP

  selector:
    app: mariadb

  ports:
    - port: 3306
      targetPort: 3306
