apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mariadb
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1

  selector:
    matchLabels:
      app: mariadb

  template:
    metadata:
      labels:
        app: mariadb

    spec:
      containers:
        - name: mariadb

          image: {{ .Values.databaseImage }}:{{ index .Chart.Annotations "mariadbVersion" }}

          ports:
            - containerPort: 3306

          env:
            - name: MARIADB_DATABASE
              value: wordpress

            - name: MARIADB_USER
              value: wordpress

            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-mariadb
                  key: password

            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-mariadb
                  key: rootPassword

          volumeMounts:
            - name: mariadb-data
              mountPath: /var/lib/mysql

      volumes:
        - name: mariadb-data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-mariadb-data
