apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-mysql"
  labels:
    app: "{{ .Release.Name }}-mysql"
spec:
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}-mysql"
    spec:
      initContainers:
      - name: "remove-lost-found"
        image: "busybox:1.25.0"
        command:  ["rm", "-fr", "/var/lib/mysql/lost+found"]
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
      containers:
      - name: "{{ .Release.Name }}-mysql"
        image: "mysql:8.0-debian "
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: {{ default "wordpress-root" .Values.mysqlroot | quote }}
        - name: MYSQL_PASSWORD
          value: {{ default "wordpress" .Values.mysqlUser | quote }}
        - name: MYSQL_USER
          value: {{ default "wordpress" .Values.mysqlUser | quote }}
        - name: MYSQL_DATABASE
          value: {{ default "wordpress" .Values.mysqlDatabase | quote }}
        ports:
        - name: mysql
          containerPort: 3306
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - "mysqladmin ping -u root -p${MYSQL_ROOT_PASSWORD}"
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.livenessProbe.successThreshold }}
          failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - "mysqladmin ping -u root -p${MYSQL_ROOT_PASSWORD}"
            {{- end }}
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.readinessProbe.successThreshold }}
          failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
