---
image:
  repository: ghcr.io/blakeblackshear/frigate
  tag:
  pullPolicy: IfNotPresent

imagePullSecrets: []

env:
  HSA_OVERRIDE_GFX_VERSION: "12.0.0"
  FRIGATE_RTSP_PASSWORD: "replaceme"
  PLUS_API_KEY: "replaceme"

envFromSecrets: []

gpu:
  nvidia:
    enabled: false
    runtimeClassName:

shmSize: 2Gi

tmpfs:
  enabled: true
  sizeLimit: 1Gi

probes:
  liveness:
    enabled: true
    initialDelaySeconds: 30
    failureThreshold: 5
    timeoutSeconds: 10
  readiness:
    enabled: true
    initialDelaySeconds: 30
    failureThreshold: 5
    timeoutSeconds: 10
  startup:
    enabled: false
    failureThreshold: 30
    periodSeconds: 10

service:
  type: ClusterIP
  port: 5000

persistence:
  config:
    enabled: true
    accessMode: ReadWriteOnce
    size: 100Mi
    skipuninstall: true

    ## Copy configMap config into volume to make writable
    ## All live changes are lost when pod restarts, but this allows
    ## an easy way to run migrations and edit config, then scrape
    ## it from the API or copy out of the pod and update local helm values
    ephemeralWritableConfigYaml: true

  media:
    enabled: true
    accessMode: ReadWriteOnce
    size: 1000Gi
    skipuninstall: true

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  #   gpu.intel.com/i915: 1
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
  #   gpu.intel.com/i915: 1

# -- Set Frigate Container Security Context
securityContext:
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000
  privileged: true

# -- Set Pod level Security Context
# -- the container level securiy context defined above
# -- will override it for frigate container
podSecurityContext:
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000
  # fsGroup: 1000
  privileged: true

extraVolumes:
  - name: dri
    hostPath:
      path: /dev/dri
      type: Directory
  - name: kfd
    hostPath:
      path: /dev/kfd
      type: CharDevice

extraVolumeMounts:
  - name: dri
    mountPath: /dev/dri
  - name: kfd
    mountPath: /dev/kfd
