name: Lint test helm charts

on: push

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up helm
        uses: azure/setup-helm@v1
        with:
          version: v3.8.1

      - name: Run helm lint
        run: helm lint grocy
