---
name: Lint test helm charts
on: push

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up helm
        uses: azure/setup-helm@v3

      - name: Run helm lint
        run: |
          helm lint jellyfin
          helm lint gitea
          helm lint invidious
